### PR TITLE
Remote Citrix certificates and use signer's cert

### PR DESCRIPTION
**Pull request by pearsonk**
Citrix no longer builds and signs certs, so no need to keep them.
As the signer is now part of the build config, we can use that to export
the signer's certificate to a known filename, which will allow modified
unattended.bat to work again.

OXT-104

Signed-off-by: Kevin Pearson <kevin.pearson.4@us.af.mil>

### CODE REVIEW

**Comment by pearsonk** [comment]
Pondered not using a static location for the output certificate file, rather using the $Company.cer and having build script mod the unattendedinstall.bat. Fell back to this approach for simplicity.

**Comment by rossphilipson** [comment]
Ok I see, so it ends up writing whatever the cert is out as ToolsSigner.cer. I think that is sufficient - at that point it is internal to the build/installer.

Do you want to take the opportunity to fix:

"$Company XenClient Tools Installer"  to either  "$Company OpenXT Tools Installer" or just "$Company Tools Installer"?

**Comment by pearsonk** [comment]
Personally, I think the XenClient branding cleanup should be separate from this. There is a lot of Citrix & XenClient that needs to be adjusted.

**Comment by dotdashnotdot** [comment]
It all looks good so far except for the fact you have no mechanism to adapt the lines:

certutil -delstore -enterprise "TrustedPublisher" "1dced972d082a6a82ca2a99fbcea3a95"
certutil -delstore -enterprise "TrustedPublisher" "6d589bf235caa049ca618dc4c2489a82"

Which are designed to remove the Citrix certificates post installation. The idea being that we don't leave the certificates behind & leave a hole for sneak installs to happen. If you don't care about such a situation then you also want to remove these lines. If you do care then you need to update the script to get the certificate's hash & do some code gen.

**Comment by pearsonk** [comment]
Excellent find. I will adjust the removal as well.

**Comment by pearsonk** [comment]
Closing, will reopen when further work done on cleanup

**Pull request closed without merging**
